// Code generated by protoc-gen-go. DO NOT EDIT.
// source: post.proto

package post_grpc

import (
	context "context"
	fmt "fmt"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ListPostsReq_Filter_OrderBy int32

const (
	ListPostsReq_Filter_DESC ListPostsReq_Filter_OrderBy = 0
	ListPostsReq_Filter_ASC  ListPostsReq_Filter_OrderBy = 1
)

var ListPostsReq_Filter_OrderBy_name = map[int32]string{
	0: "DESC",
	1: "ASC",
}

var ListPostsReq_Filter_OrderBy_value = map[string]int32{
	"DESC": 0,
	"ASC":  1,
}

func (x ListPostsReq_Filter_OrderBy) String() string {
	return proto.EnumName(ListPostsReq_Filter_OrderBy_name, int32(x))
}

func (ListPostsReq_Filter_OrderBy) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{3, 0, 0}
}

type ListPostsReq_Filter_SortBy int32

const (
	ListPostsReq_Filter_CREATED_AT ListPostsReq_Filter_SortBy = 0
	ListPostsReq_Filter_MEETING_AT ListPostsReq_Filter_SortBy = 1
)

var ListPostsReq_Filter_SortBy_name = map[int32]string{
	0: "CREATED_AT",
	1: "MEETING_AT",
}

var ListPostsReq_Filter_SortBy_value = map[string]int32{
	"CREATED_AT": 0,
	"MEETING_AT": 1,
}

func (x ListPostsReq_Filter_SortBy) String() string {
	return proto.EnumName(ListPostsReq_Filter_SortBy_name, int32(x))
}

func (ListPostsReq_Filter_SortBy) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{3, 0, 1}
}

type Post struct {
	Id                   int64                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string               `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content              string               `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	FishingSpotTypeId    int64                `protobuf:"varint,4,opt,name=fishing_spot_type_id,json=fishingSpotTypeId,proto3" json:"fishing_spot_type_id,omitempty"`
	FishTypeIds          []int64              `protobuf:"varint,5,rep,packed,name=fish_type_ids,json=fishTypeIds,proto3" json:"fish_type_ids,omitempty"`
	PrefectureId         int64                `protobuf:"varint,6,opt,name=prefecture_id,json=prefectureId,proto3" json:"prefecture_id,omitempty"`
	MeetingPlaceId       string               `protobuf:"bytes,7,opt,name=meeting_place_id,json=meetingPlaceId,proto3" json:"meeting_place_id,omitempty"`
	MeetingAt            *timestamp.Timestamp `protobuf:"bytes,8,opt,name=meeting_at,json=meetingAt,proto3" json:"meeting_at,omitempty"`
	UserId               int64                `protobuf:"varint,9,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	MaxApply             int64                `protobuf:"varint,10,opt,name=max_apply,json=maxApply,proto3" json:"max_apply,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Post) Reset()         { *m = Post{} }
func (m *Post) String() string { return proto.CompactTextString(m) }
func (*Post) ProtoMessage()    {}
func (*Post) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{0}
}

func (m *Post) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Post.Unmarshal(m, b)
}
func (m *Post) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Post.Marshal(b, m, deterministic)
}
func (m *Post) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Post.Merge(m, src)
}
func (m *Post) XXX_Size() int {
	return xxx_messageInfo_Post.Size(m)
}
func (m *Post) XXX_DiscardUnknown() {
	xxx_messageInfo_Post.DiscardUnknown(m)
}

var xxx_messageInfo_Post proto.InternalMessageInfo

func (m *Post) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Post) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Post) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Post) GetFishingSpotTypeId() int64 {
	if m != nil {
		return m.FishingSpotTypeId
	}
	return 0
}

func (m *Post) GetFishTypeIds() []int64 {
	if m != nil {
		return m.FishTypeIds
	}
	return nil
}

func (m *Post) GetPrefectureId() int64 {
	if m != nil {
		return m.PrefectureId
	}
	return 0
}

func (m *Post) GetMeetingPlaceId() string {
	if m != nil {
		return m.MeetingPlaceId
	}
	return ""
}

func (m *Post) GetMeetingAt() *timestamp.Timestamp {
	if m != nil {
		return m.MeetingAt
	}
	return nil
}

func (m *Post) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *Post) GetMaxApply() int64 {
	if m != nil {
		return m.MaxApply
	}
	return 0
}

func (m *Post) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Post) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

type ApplyPost struct {
	Id                   int64                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	PostId               int64                `protobuf:"varint,2,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	UserId               int64                `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ApplyPost) Reset()         { *m = ApplyPost{} }
func (m *ApplyPost) String() string { return proto.CompactTextString(m) }
func (*ApplyPost) ProtoMessage()    {}
func (*ApplyPost) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{1}
}

func (m *ApplyPost) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApplyPost.Unmarshal(m, b)
}
func (m *ApplyPost) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApplyPost.Marshal(b, m, deterministic)
}
func (m *ApplyPost) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplyPost.Merge(m, src)
}
func (m *ApplyPost) XXX_Size() int {
	return xxx_messageInfo_ApplyPost.Size(m)
}
func (m *ApplyPost) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplyPost.DiscardUnknown(m)
}

var xxx_messageInfo_ApplyPost proto.InternalMessageInfo

func (m *ApplyPost) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ApplyPost) GetPostId() int64 {
	if m != nil {
		return m.PostId
	}
	return 0
}

func (m *ApplyPost) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *ApplyPost) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *ApplyPost) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

type GetPostReq struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPostReq) Reset()         { *m = GetPostReq{} }
func (m *GetPostReq) String() string { return proto.CompactTextString(m) }
func (*GetPostReq) ProtoMessage()    {}
func (*GetPostReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{2}
}

func (m *GetPostReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPostReq.Unmarshal(m, b)
}
func (m *GetPostReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPostReq.Marshal(b, m, deterministic)
}
func (m *GetPostReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPostReq.Merge(m, src)
}
func (m *GetPostReq) XXX_Size() int {
	return xxx_messageInfo_GetPostReq.Size(m)
}
func (m *GetPostReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPostReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetPostReq proto.InternalMessageInfo

func (m *GetPostReq) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ListPostsReq struct {
	Filter               *ListPostsReq_Filter `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	PageSize             int64                `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken            string               `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ListPostsReq) Reset()         { *m = ListPostsReq{} }
func (m *ListPostsReq) String() string { return proto.CompactTextString(m) }
func (*ListPostsReq) ProtoMessage()    {}
func (*ListPostsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{3}
}

func (m *ListPostsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPostsReq.Unmarshal(m, b)
}
func (m *ListPostsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPostsReq.Marshal(b, m, deterministic)
}
func (m *ListPostsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPostsReq.Merge(m, src)
}
func (m *ListPostsReq) XXX_Size() int {
	return xxx_messageInfo_ListPostsReq.Size(m)
}
func (m *ListPostsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPostsReq.DiscardUnknown(m)
}

var xxx_messageInfo_ListPostsReq proto.InternalMessageInfo

func (m *ListPostsReq) GetFilter() *ListPostsReq_Filter {
	if m != nil {
		return m.Filter
	}
	return nil
}

func (m *ListPostsReq) GetPageSize() int64 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ListPostsReq) GetPageToken() string {
	if m != nil {
		return m.PageToken
	}
	return ""
}

type ListPostsReq_Filter struct {
	PrefectureId         int64                       `protobuf:"varint,1,opt,name=prefecture_id,json=prefectureId,proto3" json:"prefecture_id,omitempty"`
	FishingSpotTypeId    int64                       `protobuf:"varint,2,opt,name=fishing_spot_type_id,json=fishingSpotTypeId,proto3" json:"fishing_spot_type_id,omitempty"`
	FishTypeIds          []int64                     `protobuf:"varint,3,rep,packed,name=fish_type_ids,json=fishTypeIds,proto3" json:"fish_type_ids,omitempty"`
	MeetingAtFrom        *timestamp.Timestamp        `protobuf:"bytes,4,opt,name=meeting_at_from,json=meetingAtFrom,proto3" json:"meeting_at_from,omitempty"`
	MeetingAtTo          *timestamp.Timestamp        `protobuf:"bytes,5,opt,name=meeting_at_to,json=meetingAtTo,proto3" json:"meeting_at_to,omitempty"`
	CanApply             bool                        `protobuf:"varint,6,opt,name=can_apply,json=canApply,proto3" json:"can_apply,omitempty"`
	OrderBy              ListPostsReq_Filter_OrderBy `protobuf:"varint,7,opt,name=order_by,json=orderBy,proto3,enum=post_grpc.ListPostsReq_Filter_OrderBy" json:"order_by,omitempty"`
	SortBy               ListPostsReq_Filter_SortBy  `protobuf:"varint,8,opt,name=sort_by,json=sortBy,proto3,enum=post_grpc.ListPostsReq_Filter_SortBy" json:"sort_by,omitempty"`
	UserId               int64                       `protobuf:"varint,9,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *ListPostsReq_Filter) Reset()         { *m = ListPostsReq_Filter{} }
func (m *ListPostsReq_Filter) String() string { return proto.CompactTextString(m) }
func (*ListPostsReq_Filter) ProtoMessage()    {}
func (*ListPostsReq_Filter) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{3, 0}
}

func (m *ListPostsReq_Filter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPostsReq_Filter.Unmarshal(m, b)
}
func (m *ListPostsReq_Filter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPostsReq_Filter.Marshal(b, m, deterministic)
}
func (m *ListPostsReq_Filter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPostsReq_Filter.Merge(m, src)
}
func (m *ListPostsReq_Filter) XXX_Size() int {
	return xxx_messageInfo_ListPostsReq_Filter.Size(m)
}
func (m *ListPostsReq_Filter) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPostsReq_Filter.DiscardUnknown(m)
}

var xxx_messageInfo_ListPostsReq_Filter proto.InternalMessageInfo

func (m *ListPostsReq_Filter) GetPrefectureId() int64 {
	if m != nil {
		return m.PrefectureId
	}
	return 0
}

func (m *ListPostsReq_Filter) GetFishingSpotTypeId() int64 {
	if m != nil {
		return m.FishingSpotTypeId
	}
	return 0
}

func (m *ListPostsReq_Filter) GetFishTypeIds() []int64 {
	if m != nil {
		return m.FishTypeIds
	}
	return nil
}

func (m *ListPostsReq_Filter) GetMeetingAtFrom() *timestamp.Timestamp {
	if m != nil {
		return m.MeetingAtFrom
	}
	return nil
}

func (m *ListPostsReq_Filter) GetMeetingAtTo() *timestamp.Timestamp {
	if m != nil {
		return m.MeetingAtTo
	}
	return nil
}

func (m *ListPostsReq_Filter) GetCanApply() bool {
	if m != nil {
		return m.CanApply
	}
	return false
}

func (m *ListPostsReq_Filter) GetOrderBy() ListPostsReq_Filter_OrderBy {
	if m != nil {
		return m.OrderBy
	}
	return ListPostsReq_Filter_DESC
}

func (m *ListPostsReq_Filter) GetSortBy() ListPostsReq_Filter_SortBy {
	if m != nil {
		return m.SortBy
	}
	return ListPostsReq_Filter_CREATED_AT
}

func (m *ListPostsReq_Filter) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type ListPostsRes struct {
	Posts                []*Post  `protobuf:"bytes,1,rep,name=posts,proto3" json:"posts,omitempty"`
	NextPageToken        string   `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListPostsRes) Reset()         { *m = ListPostsRes{} }
func (m *ListPostsRes) String() string { return proto.CompactTextString(m) }
func (*ListPostsRes) ProtoMessage()    {}
func (*ListPostsRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{4}
}

func (m *ListPostsRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPostsRes.Unmarshal(m, b)
}
func (m *ListPostsRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPostsRes.Marshal(b, m, deterministic)
}
func (m *ListPostsRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPostsRes.Merge(m, src)
}
func (m *ListPostsRes) XXX_Size() int {
	return xxx_messageInfo_ListPostsRes.Size(m)
}
func (m *ListPostsRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPostsRes.DiscardUnknown(m)
}

var xxx_messageInfo_ListPostsRes proto.InternalMessageInfo

func (m *ListPostsRes) GetPosts() []*Post {
	if m != nil {
		return m.Posts
	}
	return nil
}

func (m *ListPostsRes) GetNextPageToken() string {
	if m != nil {
		return m.NextPageToken
	}
	return ""
}

type CreatePostReq struct {
	Title                string               `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Content              string               `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	FishingSpotTypeId    int64                `protobuf:"varint,3,opt,name=fishing_spot_type_id,json=fishingSpotTypeId,proto3" json:"fishing_spot_type_id,omitempty"`
	FishTypeIds          []int64              `protobuf:"varint,4,rep,packed,name=fish_type_ids,json=fishTypeIds,proto3" json:"fish_type_ids,omitempty"`
	PrefectureId         int64                `protobuf:"varint,5,opt,name=prefecture_id,json=prefectureId,proto3" json:"prefecture_id,omitempty"`
	MeetingPlaceId       string               `protobuf:"bytes,6,opt,name=meeting_place_id,json=meetingPlaceId,proto3" json:"meeting_place_id,omitempty"`
	MeetingAt            *timestamp.Timestamp `protobuf:"bytes,7,opt,name=meeting_at,json=meetingAt,proto3" json:"meeting_at,omitempty"`
	MaxApply             int64                `protobuf:"varint,8,opt,name=max_apply,json=maxApply,proto3" json:"max_apply,omitempty"`
	UserId               int64                `protobuf:"varint,9,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *CreatePostReq) Reset()         { *m = CreatePostReq{} }
func (m *CreatePostReq) String() string { return proto.CompactTextString(m) }
func (*CreatePostReq) ProtoMessage()    {}
func (*CreatePostReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{5}
}

func (m *CreatePostReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePostReq.Unmarshal(m, b)
}
func (m *CreatePostReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePostReq.Marshal(b, m, deterministic)
}
func (m *CreatePostReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePostReq.Merge(m, src)
}
func (m *CreatePostReq) XXX_Size() int {
	return xxx_messageInfo_CreatePostReq.Size(m)
}
func (m *CreatePostReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePostReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePostReq proto.InternalMessageInfo

func (m *CreatePostReq) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *CreatePostReq) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *CreatePostReq) GetFishingSpotTypeId() int64 {
	if m != nil {
		return m.FishingSpotTypeId
	}
	return 0
}

func (m *CreatePostReq) GetFishTypeIds() []int64 {
	if m != nil {
		return m.FishTypeIds
	}
	return nil
}

func (m *CreatePostReq) GetPrefectureId() int64 {
	if m != nil {
		return m.PrefectureId
	}
	return 0
}

func (m *CreatePostReq) GetMeetingPlaceId() string {
	if m != nil {
		return m.MeetingPlaceId
	}
	return ""
}

func (m *CreatePostReq) GetMeetingAt() *timestamp.Timestamp {
	if m != nil {
		return m.MeetingAt
	}
	return nil
}

func (m *CreatePostReq) GetMaxApply() int64 {
	if m != nil {
		return m.MaxApply
	}
	return 0
}

func (m *CreatePostReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type UpdatePostReq struct {
	Id                   int64                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string               `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content              string               `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	FishingSpotTypeId    int64                `protobuf:"varint,4,opt,name=fishing_spot_type_id,json=fishingSpotTypeId,proto3" json:"fishing_spot_type_id,omitempty"`
	FishTypeIds          []int64              `protobuf:"varint,5,rep,packed,name=fish_type_ids,json=fishTypeIds,proto3" json:"fish_type_ids,omitempty"`
	PrefectureId         int64                `protobuf:"varint,6,opt,name=prefecture_id,json=prefectureId,proto3" json:"prefecture_id,omitempty"`
	MeetingPlaceId       string               `protobuf:"bytes,7,opt,name=meeting_place_id,json=meetingPlaceId,proto3" json:"meeting_place_id,omitempty"`
	MeetingAt            *timestamp.Timestamp `protobuf:"bytes,8,opt,name=meeting_at,json=meetingAt,proto3" json:"meeting_at,omitempty"`
	MaxApply             int64                `protobuf:"varint,9,opt,name=max_apply,json=maxApply,proto3" json:"max_apply,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *UpdatePostReq) Reset()         { *m = UpdatePostReq{} }
func (m *UpdatePostReq) String() string { return proto.CompactTextString(m) }
func (*UpdatePostReq) ProtoMessage()    {}
func (*UpdatePostReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{6}
}

func (m *UpdatePostReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePostReq.Unmarshal(m, b)
}
func (m *UpdatePostReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePostReq.Marshal(b, m, deterministic)
}
func (m *UpdatePostReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePostReq.Merge(m, src)
}
func (m *UpdatePostReq) XXX_Size() int {
	return xxx_messageInfo_UpdatePostReq.Size(m)
}
func (m *UpdatePostReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePostReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePostReq proto.InternalMessageInfo

func (m *UpdatePostReq) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdatePostReq) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *UpdatePostReq) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *UpdatePostReq) GetFishingSpotTypeId() int64 {
	if m != nil {
		return m.FishingSpotTypeId
	}
	return 0
}

func (m *UpdatePostReq) GetFishTypeIds() []int64 {
	if m != nil {
		return m.FishTypeIds
	}
	return nil
}

func (m *UpdatePostReq) GetPrefectureId() int64 {
	if m != nil {
		return m.PrefectureId
	}
	return 0
}

func (m *UpdatePostReq) GetMeetingPlaceId() string {
	if m != nil {
		return m.MeetingPlaceId
	}
	return ""
}

func (m *UpdatePostReq) GetMeetingAt() *timestamp.Timestamp {
	if m != nil {
		return m.MeetingAt
	}
	return nil
}

func (m *UpdatePostReq) GetMaxApply() int64 {
	if m != nil {
		return m.MaxApply
	}
	return 0
}

type DeletePostReq struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeletePostReq) Reset()         { *m = DeletePostReq{} }
func (m *DeletePostReq) String() string { return proto.CompactTextString(m) }
func (*DeletePostReq) ProtoMessage()    {}
func (*DeletePostReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{7}
}

func (m *DeletePostReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletePostReq.Unmarshal(m, b)
}
func (m *DeletePostReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletePostReq.Marshal(b, m, deterministic)
}
func (m *DeletePostReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletePostReq.Merge(m, src)
}
func (m *DeletePostReq) XXX_Size() int {
	return xxx_messageInfo_DeletePostReq.Size(m)
}
func (m *DeletePostReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletePostReq.DiscardUnknown(m)
}

var xxx_messageInfo_DeletePostReq proto.InternalMessageInfo

func (m *DeletePostReq) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DeletePostRes struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeletePostRes) Reset()         { *m = DeletePostRes{} }
func (m *DeletePostRes) String() string { return proto.CompactTextString(m) }
func (*DeletePostRes) ProtoMessage()    {}
func (*DeletePostRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{8}
}

func (m *DeletePostRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletePostRes.Unmarshal(m, b)
}
func (m *DeletePostRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletePostRes.Marshal(b, m, deterministic)
}
func (m *DeletePostRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletePostRes.Merge(m, src)
}
func (m *DeletePostRes) XXX_Size() int {
	return xxx_messageInfo_DeletePostRes.Size(m)
}
func (m *DeletePostRes) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletePostRes.DiscardUnknown(m)
}

var xxx_messageInfo_DeletePostRes proto.InternalMessageInfo

func (m *DeletePostRes) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type GetApplyPostReq struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetApplyPostReq) Reset()         { *m = GetApplyPostReq{} }
func (m *GetApplyPostReq) String() string { return proto.CompactTextString(m) }
func (*GetApplyPostReq) ProtoMessage()    {}
func (*GetApplyPostReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{9}
}

func (m *GetApplyPostReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetApplyPostReq.Unmarshal(m, b)
}
func (m *GetApplyPostReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetApplyPostReq.Marshal(b, m, deterministic)
}
func (m *GetApplyPostReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetApplyPostReq.Merge(m, src)
}
func (m *GetApplyPostReq) XXX_Size() int {
	return xxx_messageInfo_GetApplyPostReq.Size(m)
}
func (m *GetApplyPostReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetApplyPostReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetApplyPostReq proto.InternalMessageInfo

func (m *GetApplyPostReq) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ListApplyPostsReq struct {
	Filter               *ListApplyPostsReq_Filter `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *ListApplyPostsReq) Reset()         { *m = ListApplyPostsReq{} }
func (m *ListApplyPostsReq) String() string { return proto.CompactTextString(m) }
func (*ListApplyPostsReq) ProtoMessage()    {}
func (*ListApplyPostsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{10}
}

func (m *ListApplyPostsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListApplyPostsReq.Unmarshal(m, b)
}
func (m *ListApplyPostsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListApplyPostsReq.Marshal(b, m, deterministic)
}
func (m *ListApplyPostsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListApplyPostsReq.Merge(m, src)
}
func (m *ListApplyPostsReq) XXX_Size() int {
	return xxx_messageInfo_ListApplyPostsReq.Size(m)
}
func (m *ListApplyPostsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ListApplyPostsReq.DiscardUnknown(m)
}

var xxx_messageInfo_ListApplyPostsReq proto.InternalMessageInfo

func (m *ListApplyPostsReq) GetFilter() *ListApplyPostsReq_Filter {
	if m != nil {
		return m.Filter
	}
	return nil
}

type ListApplyPostsReq_Filter struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PostId               int64    `protobuf:"varint,2,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListApplyPostsReq_Filter) Reset()         { *m = ListApplyPostsReq_Filter{} }
func (m *ListApplyPostsReq_Filter) String() string { return proto.CompactTextString(m) }
func (*ListApplyPostsReq_Filter) ProtoMessage()    {}
func (*ListApplyPostsReq_Filter) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{10, 0}
}

func (m *ListApplyPostsReq_Filter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListApplyPostsReq_Filter.Unmarshal(m, b)
}
func (m *ListApplyPostsReq_Filter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListApplyPostsReq_Filter.Marshal(b, m, deterministic)
}
func (m *ListApplyPostsReq_Filter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListApplyPostsReq_Filter.Merge(m, src)
}
func (m *ListApplyPostsReq_Filter) XXX_Size() int {
	return xxx_messageInfo_ListApplyPostsReq_Filter.Size(m)
}
func (m *ListApplyPostsReq_Filter) XXX_DiscardUnknown() {
	xxx_messageInfo_ListApplyPostsReq_Filter.DiscardUnknown(m)
}

var xxx_messageInfo_ListApplyPostsReq_Filter proto.InternalMessageInfo

func (m *ListApplyPostsReq_Filter) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *ListApplyPostsReq_Filter) GetPostId() int64 {
	if m != nil {
		return m.PostId
	}
	return 0
}

type ListApplyPostsRes struct {
	ApplyPosts           []*ApplyPost `protobuf:"bytes,1,rep,name=apply_posts,json=applyPosts,proto3" json:"apply_posts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ListApplyPostsRes) Reset()         { *m = ListApplyPostsRes{} }
func (m *ListApplyPostsRes) String() string { return proto.CompactTextString(m) }
func (*ListApplyPostsRes) ProtoMessage()    {}
func (*ListApplyPostsRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{11}
}

func (m *ListApplyPostsRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListApplyPostsRes.Unmarshal(m, b)
}
func (m *ListApplyPostsRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListApplyPostsRes.Marshal(b, m, deterministic)
}
func (m *ListApplyPostsRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListApplyPostsRes.Merge(m, src)
}
func (m *ListApplyPostsRes) XXX_Size() int {
	return xxx_messageInfo_ListApplyPostsRes.Size(m)
}
func (m *ListApplyPostsRes) XXX_DiscardUnknown() {
	xxx_messageInfo_ListApplyPostsRes.DiscardUnknown(m)
}

var xxx_messageInfo_ListApplyPostsRes proto.InternalMessageInfo

func (m *ListApplyPostsRes) GetApplyPosts() []*ApplyPost {
	if m != nil {
		return m.ApplyPosts
	}
	return nil
}

type BatchGetApplyPostsByPostIDsReq struct {
	PostIds              []int64  `protobuf:"varint,1,rep,packed,name=post_ids,json=postIds,proto3" json:"post_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BatchGetApplyPostsByPostIDsReq) Reset()         { *m = BatchGetApplyPostsByPostIDsReq{} }
func (m *BatchGetApplyPostsByPostIDsReq) String() string { return proto.CompactTextString(m) }
func (*BatchGetApplyPostsByPostIDsReq) ProtoMessage()    {}
func (*BatchGetApplyPostsByPostIDsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{12}
}

func (m *BatchGetApplyPostsByPostIDsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BatchGetApplyPostsByPostIDsReq.Unmarshal(m, b)
}
func (m *BatchGetApplyPostsByPostIDsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BatchGetApplyPostsByPostIDsReq.Marshal(b, m, deterministic)
}
func (m *BatchGetApplyPostsByPostIDsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BatchGetApplyPostsByPostIDsReq.Merge(m, src)
}
func (m *BatchGetApplyPostsByPostIDsReq) XXX_Size() int {
	return xxx_messageInfo_BatchGetApplyPostsByPostIDsReq.Size(m)
}
func (m *BatchGetApplyPostsByPostIDsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_BatchGetApplyPostsByPostIDsReq.DiscardUnknown(m)
}

var xxx_messageInfo_BatchGetApplyPostsByPostIDsReq proto.InternalMessageInfo

func (m *BatchGetApplyPostsByPostIDsReq) GetPostIds() []int64 {
	if m != nil {
		return m.PostIds
	}
	return nil
}

type BatchGetApplyPostsByPostIDsRes struct {
	ApplyPosts           []*ApplyPost `protobuf:"bytes,1,rep,name=apply_posts,json=applyPosts,proto3" json:"apply_posts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *BatchGetApplyPostsByPostIDsRes) Reset()         { *m = BatchGetApplyPostsByPostIDsRes{} }
func (m *BatchGetApplyPostsByPostIDsRes) String() string { return proto.CompactTextString(m) }
func (*BatchGetApplyPostsByPostIDsRes) ProtoMessage()    {}
func (*BatchGetApplyPostsByPostIDsRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{13}
}

func (m *BatchGetApplyPostsByPostIDsRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BatchGetApplyPostsByPostIDsRes.Unmarshal(m, b)
}
func (m *BatchGetApplyPostsByPostIDsRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BatchGetApplyPostsByPostIDsRes.Marshal(b, m, deterministic)
}
func (m *BatchGetApplyPostsByPostIDsRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BatchGetApplyPostsByPostIDsRes.Merge(m, src)
}
func (m *BatchGetApplyPostsByPostIDsRes) XXX_Size() int {
	return xxx_messageInfo_BatchGetApplyPostsByPostIDsRes.Size(m)
}
func (m *BatchGetApplyPostsByPostIDsRes) XXX_DiscardUnknown() {
	xxx_messageInfo_BatchGetApplyPostsByPostIDsRes.DiscardUnknown(m)
}

var xxx_messageInfo_BatchGetApplyPostsByPostIDsRes proto.InternalMessageInfo

func (m *BatchGetApplyPostsByPostIDsRes) GetApplyPosts() []*ApplyPost {
	if m != nil {
		return m.ApplyPosts
	}
	return nil
}

type CreateApplyPostReq struct {
	PostId               int64    `protobuf:"varint,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	UserId               int64    `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateApplyPostReq) Reset()         { *m = CreateApplyPostReq{} }
func (m *CreateApplyPostReq) String() string { return proto.CompactTextString(m) }
func (*CreateApplyPostReq) ProtoMessage()    {}
func (*CreateApplyPostReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{14}
}

func (m *CreateApplyPostReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateApplyPostReq.Unmarshal(m, b)
}
func (m *CreateApplyPostReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateApplyPostReq.Marshal(b, m, deterministic)
}
func (m *CreateApplyPostReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateApplyPostReq.Merge(m, src)
}
func (m *CreateApplyPostReq) XXX_Size() int {
	return xxx_messageInfo_CreateApplyPostReq.Size(m)
}
func (m *CreateApplyPostReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateApplyPostReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateApplyPostReq proto.InternalMessageInfo

func (m *CreateApplyPostReq) GetPostId() int64 {
	if m != nil {
		return m.PostId
	}
	return 0
}

func (m *CreateApplyPostReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type DeleteApplyPostReq struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteApplyPostReq) Reset()         { *m = DeleteApplyPostReq{} }
func (m *DeleteApplyPostReq) String() string { return proto.CompactTextString(m) }
func (*DeleteApplyPostReq) ProtoMessage()    {}
func (*DeleteApplyPostReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{15}
}

func (m *DeleteApplyPostReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteApplyPostReq.Unmarshal(m, b)
}
func (m *DeleteApplyPostReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteApplyPostReq.Marshal(b, m, deterministic)
}
func (m *DeleteApplyPostReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteApplyPostReq.Merge(m, src)
}
func (m *DeleteApplyPostReq) XXX_Size() int {
	return xxx_messageInfo_DeleteApplyPostReq.Size(m)
}
func (m *DeleteApplyPostReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteApplyPostReq.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteApplyPostReq proto.InternalMessageInfo

func (m *DeleteApplyPostReq) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterEnum("post_grpc.ListPostsReq_Filter_OrderBy", ListPostsReq_Filter_OrderBy_name, ListPostsReq_Filter_OrderBy_value)
	proto.RegisterEnum("post_grpc.ListPostsReq_Filter_SortBy", ListPostsReq_Filter_SortBy_name, ListPostsReq_Filter_SortBy_value)
	proto.RegisterType((*Post)(nil), "post_grpc.Post")
	proto.RegisterType((*ApplyPost)(nil), "post_grpc.ApplyPost")
	proto.RegisterType((*GetPostReq)(nil), "post_grpc.GetPostReq")
	proto.RegisterType((*ListPostsReq)(nil), "post_grpc.ListPostsReq")
	proto.RegisterType((*ListPostsReq_Filter)(nil), "post_grpc.ListPostsReq.Filter")
	proto.RegisterType((*ListPostsRes)(nil), "post_grpc.ListPostsRes")
	proto.RegisterType((*CreatePostReq)(nil), "post_grpc.CreatePostReq")
	proto.RegisterType((*UpdatePostReq)(nil), "post_grpc.UpdatePostReq")
	proto.RegisterType((*DeletePostReq)(nil), "post_grpc.DeletePostReq")
	proto.RegisterType((*DeletePostRes)(nil), "post_grpc.DeletePostRes")
	proto.RegisterType((*GetApplyPostReq)(nil), "post_grpc.GetApplyPostReq")
	proto.RegisterType((*ListApplyPostsReq)(nil), "post_grpc.ListApplyPostsReq")
	proto.RegisterType((*ListApplyPostsReq_Filter)(nil), "post_grpc.ListApplyPostsReq.Filter")
	proto.RegisterType((*ListApplyPostsRes)(nil), "post_grpc.ListApplyPostsRes")
	proto.RegisterType((*BatchGetApplyPostsByPostIDsReq)(nil), "post_grpc.BatchGetApplyPostsByPostIDsReq")
	proto.RegisterType((*BatchGetApplyPostsByPostIDsRes)(nil), "post_grpc.BatchGetApplyPostsByPostIDsRes")
	proto.RegisterType((*CreateApplyPostReq)(nil), "post_grpc.CreateApplyPostReq")
	proto.RegisterType((*DeleteApplyPostReq)(nil), "post_grpc.DeleteApplyPostReq")
}

func init() { proto.RegisterFile("post.proto", fileDescriptor_e114ad14deab1dd1) }

var fileDescriptor_e114ad14deab1dd1 = []byte{
	// 1267 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x57, 0xcd, 0x73, 0xdb, 0x44,
	0x14, 0xef, 0x5a, 0xb6, 0x25, 0x3d, 0xc7, 0xb1, 0xbb, 0x13, 0x88, 0x50, 0xfa, 0xe1, 0x51, 0x3f,
	0x46, 0x65, 0xc0, 0x19, 0xc2, 0x47, 0xa1, 0x1d, 0x3a, 0xb1, 0x92, 0xb4, 0x35, 0x14, 0xe8, 0x28,
	0x66, 0xe0, 0xc2, 0x68, 0x54, 0x6b, 0x93, 0x6a, 0xb0, 0x2d, 0xa1, 0xdd, 0x74, 0x9a, 0x1e, 0x39,
	0x32, 0x9c, 0xfa, 0xa7, 0x30, 0x5c, 0x39, 0x71, 0x61, 0x86, 0x0b, 0xfc, 0x0d, 0xfc, 0x17, 0xbe,
	0xc0, 0xec, 0x4a, 0xb2, 0x3e, 0x1c, 0xc7, 0x49, 0x86, 0x53, 0xbc, 0xbb, 0xbf, 0xf7, 0xf6, 0xbd,
	0x7d, 0xbf, 0xdf, 0x7b, 0x0a, 0x40, 0x18, 0x50, 0xd6, 0x0d, 0xa3, 0x80, 0x05, 0x58, 0xe5, 0xbf,
	0x9d, 0xc3, 0x28, 0x1c, 0xea, 0xeb, 0x2f, 0xdc, 0x91, 0xef, 0xb9, 0x8c, 0x6c, 0xa6, 0x3f, 0x62,
	0x8c, 0x7e, 0xfd, 0x30, 0x08, 0x0e, 0x47, 0x64, 0x53, 0xac, 0x9e, 0x1d, 0x1d, 0x6c, 0x32, 0x7f,
	0x4c, 0x28, 0x73, 0xc7, 0x61, 0x02, 0xd8, 0x28, 0x03, 0xc8, 0x38, 0x64, 0xc7, 0xf1, 0xa1, 0xf1,
	0xb7, 0x04, 0xd5, 0xa7, 0x01, 0x65, 0x78, 0x15, 0x2a, 0xbe, 0xa7, 0xa1, 0x0e, 0x32, 0x25, 0xbb,
	0xe2, 0x7b, 0x78, 0x0d, 0x6a, 0xcc, 0x67, 0x23, 0xa2, 0x55, 0x3a, 0xc8, 0x54, 0xed, 0x78, 0x81,
	0x35, 0x90, 0x87, 0xc1, 0x84, 0x91, 0x09, 0xd3, 0x24, 0xb1, 0x9f, 0x2e, 0xf1, 0x26, 0xac, 0x1d,
	0xf8, 0xf4, 0xb9, 0x3f, 0x39, 0x74, 0x68, 0x18, 0x30, 0x87, 0x1d, 0x87, 0xc4, 0xf1, 0x3d, 0xad,
	0x2a, 0x3c, 0x5e, 0x4e, 0xce, 0xf6, 0xc3, 0x80, 0x0d, 0x8e, 0x43, 0xd2, 0xf7, 0xb0, 0x01, 0x4d,
	0xbe, 0x99, 0x02, 0xa9, 0x56, 0xeb, 0x48, 0xa6, 0x64, 0x37, 0xf8, 0x66, 0x0c, 0xa1, 0xf8, 0x06,
	0x34, 0xc3, 0x88, 0x1c, 0x90, 0x21, 0x3b, 0x8a, 0x84, 0xb7, 0xba, 0xf0, 0xb6, 0x92, 0x6d, 0xf6,
	0x3d, 0x6c, 0x42, 0x7b, 0x4c, 0x08, 0xe3, 0x37, 0x87, 0x23, 0x77, 0x28, 0x70, 0xb2, 0x08, 0x6e,
	0x35, 0xd9, 0x7f, 0xca, 0xb7, 0xfb, 0x1e, 0xfe, 0x04, 0x20, 0x45, 0xba, 0x4c, 0x53, 0x3a, 0xc8,
	0x6c, 0x6c, 0xe9, 0xdd, 0xf8, 0x79, 0xba, 0xe9, 0xf3, 0x74, 0x07, 0xe9, 0xfb, 0xd9, 0x6a, 0x82,
	0xee, 0x31, 0xbc, 0x0e, 0xf2, 0x11, 0x25, 0x11, 0xf7, 0xad, 0x8a, 0x18, 0xea, 0x7c, 0xd9, 0xf7,
	0xf0, 0x06, 0xa8, 0x63, 0xf7, 0xa5, 0xe3, 0x86, 0xe1, 0xe8, 0x58, 0x03, 0x71, 0xa4, 0x8c, 0xdd,
	0x97, 0x3d, 0xbe, 0xe6, 0x17, 0x0e, 0x23, 0xe2, 0x32, 0xe2, 0xf1, 0x0b, 0x1b, 0xcb, 0x2f, 0x4c,
	0xd0, 0x3d, 0xc6, 0x4d, 0x8f, 0x42, 0x2f, 0x35, 0x5d, 0x59, 0x6e, 0x9a, 0xa0, 0x7b, 0xcc, 0xf8,
	0x1d, 0x81, 0x2a, 0xee, 0x3f, 0xb1, 0xb0, 0xeb, 0x20, 0x0b, 0x56, 0xf9, 0x9e, 0x28, 0xad, 0x64,
	0xd7, 0xf9, 0xb2, 0xef, 0xe5, 0x53, 0x94, 0x0a, 0x29, 0x16, 0xb3, 0xa8, 0x5e, 0x3c, 0x8b, 0xda,
	0x79, 0xb2, 0xb8, 0x05, 0xf0, 0x88, 0x30, 0x9e, 0x82, 0x4d, 0x7e, 0xc0, 0xeb, 0x59, 0x16, 0x96,
	0x3c, 0xb5, 0xaa, 0x46, 0xc5, 0x44, 0x3c, 0x1d, 0xe3, 0x9f, 0x1a, 0xac, 0x3c, 0xf1, 0xa9, 0x00,
	0x52, 0x8e, 0xdc, 0x86, 0xfa, 0x81, 0x3f, 0x62, 0x24, 0x12, 0xe8, 0xc6, 0xd6, 0xb5, 0xee, 0x4c,
	0x44, 0xdd, 0x3c, 0xb0, 0xfb, 0x50, 0xa0, 0x2c, 0x65, 0x6a, 0xd5, 0x7e, 0x42, 0x95, 0x36, 0xb2,
	0x13, 0x3b, 0x7c, 0x13, 0xd4, 0xd0, 0x3d, 0x24, 0x0e, 0xf5, 0x5f, 0xc5, 0xf4, 0x4f, 0xaf, 0xd4,
	0xae, 0xd9, 0x0a, 0x3f, 0xd9, 0xf7, 0x5f, 0x11, 0x7c, 0x15, 0x40, 0xa0, 0x58, 0xf0, 0x3d, 0x99,
	0x24, 0x6a, 0x10, 0x76, 0x03, 0xbe, 0xa1, 0xff, 0x59, 0x85, 0x7a, 0x7c, 0x03, 0x7e, 0xa7, 0xcc,
	0xe2, 0x7c, 0x1a, 0xda, 0x66, 0x89, 0xce, 0x1f, 0x2f, 0x10, 0x52, 0x21, 0x90, 0xea, 0x49, 0x8a,
	0xda, 0x2e, 0x2b, 0x4a, 0xe2, 0x8a, 0xb2, 0xae, 0x4c, 0x2d, 0xf5, 0x35, 0xaa, 0x1b, 0xdc, 0xce,
	0x99, 0x5a, 0xb5, 0xd7, 0xa8, 0xa2, 0xa0, 0xf8, 0xaf, 0x86, 0x8a, 0x7a, 0xb3, 0xa0, 0x95, 0x09,
	0xc4, 0x39, 0x88, 0x82, 0xf1, 0x19, 0xca, 0xdd, 0x9c, 0xa9, 0xe4, 0x61, 0x14, 0x8c, 0xf1, 0x03,
	0x68, 0xe6, 0x7c, 0xb0, 0xe0, 0x0c, 0x55, 0x6f, 0xcc, 0x3c, 0x0c, 0x02, 0x2e, 0xa8, 0xa1, 0x3b,
	0x49, 0x04, 0xc5, 0xf5, 0xae, 0xd8, 0xca, 0xd0, 0x9d, 0xc4, 0x82, 0xfa, 0x1c, 0x94, 0x20, 0xf2,
	0x48, 0xe4, 0x3c, 0x3b, 0x16, 0x1a, 0x5f, 0xdd, 0xba, 0x7d, 0x7a, 0x79, 0xbb, 0x5f, 0x71, 0xb8,
	0x75, 0x2c, 0xca, 0xfc, 0xa3, 0x28, 0xb3, 0x1c, 0xc4, 0x5b, 0xf8, 0x31, 0xc8, 0x34, 0x88, 0x18,
	0xf7, 0xa5, 0x08, 0x5f, 0xb7, 0x96, 0xf8, 0xda, 0x0f, 0x22, 0x56, 0x70, 0x55, 0xa7, 0x62, 0x67,
	0x61, 0x77, 0x30, 0xae, 0x80, 0x9c, 0x04, 0x80, 0x15, 0xa8, 0xee, 0xee, 0xed, 0xef, 0xb4, 0x2f,
	0x61, 0x19, 0xa4, 0xde, 0xfe, 0x4e, 0x1b, 0x19, 0x26, 0xd4, 0x63, 0x97, 0x78, 0x15, 0x60, 0xc7,
	0xde, 0xeb, 0x0d, 0xf6, 0x76, 0x9d, 0xde, 0xa0, 0x7d, 0x89, 0xaf, 0xbf, 0xd8, 0xdb, 0x1b, 0xf4,
	0xbf, 0x7c, 0xc4, 0xd7, 0xc8, 0xf8, 0xae, 0x40, 0x72, 0x8a, 0x6f, 0x41, 0x8d, 0x87, 0x4a, 0x35,
	0xd4, 0x91, 0xcc, 0xc6, 0x56, 0x2b, 0x17, 0xb8, 0x50, 0x4c, 0x7c, 0x8a, 0x6f, 0x43, 0x6b, 0x42,
	0x5e, 0x32, 0x27, 0x47, 0xd4, 0xb8, 0x9d, 0x37, 0xf9, 0xf6, 0xd3, 0x94, 0xac, 0xc6, 0x6f, 0x12,
	0x34, 0x77, 0x84, 0x68, 0x53, 0xbd, 0x5d, 0x4f, 0xdb, 0x3f, 0xe7, 0xaa, 0x6a, 0xa9, 0x53, 0xab,
	0x1e, 0x55, 0xdb, 0x48, 0x5b, 0x4b, 0x27, 0xc1, 0xcd, 0x6c, 0x12, 0x08, 0x97, 0x16, 0x4c, 0x2d,
	0x39, 0xaa, 0xb5, 0x91, 0xf6, 0x57, 0x2b, 0x9b, 0x0a, 0xf7, 0x16, 0x90, 0x59, 0x34, 0x18, 0xe1,
	0xd5, 0xa8, 0x6a, 0x55, 0x13, 0x9d, 0x44, 0xe7, 0x8f, 0xca, 0x74, 0xae, 0x0a, 0x3a, 0xe3, 0xa9,
	0xd5, 0x7a, 0x8d, 0x56, 0x14, 0xa4, 0x21, 0x83, 0x5b, 0x3b, 0x66, 0x89, 0xc4, 0xdd, 0xb2, 0xdc,
	0x6a, 0xf9, 0xcb, 0x36, 0x4d, 0x54, 0x12, 0xdc, 0x07, 0x27, 0xcc, 0x8f, 0x7a, 0x3e, 0xa5, 0x0d,
	0xed, 0x5f, 0x34, 0x37, 0x4b, 0x76, 0x0a, 0xb3, 0x44, 0x5e, 0xc6, 0x71, 0x41, 0x9a, 0x5f, 0x50,
	0x65, 0x1b, 0xe5, 0xa7, 0xca, 0xcd, 0xfc, 0xf0, 0x50, 0x8a, 0xcd, 0x2d, 0x9b, 0x22, 0x9d, 0x12,
	0xbb, 0x32, 0x4c, 0x4a, 0xb3, 0x5f, 0x25, 0x68, 0x7e, 0x2d, 0x3a, 0xe7, 0xb2, 0x7e, 0x99, 0x15,
	0xb6, 0xb2, 0xbc, 0xb0, 0xd2, 0xf9, 0x0b, 0x5b, 0xbd, 0x48, 0x61, 0x6b, 0x17, 0x2c, 0x6c, 0xfd,
	0xfc, 0x85, 0x95, 0xcf, 0x59, 0x58, 0xe5, 0x7f, 0x28, 0xac, 0xba, 0xa0, 0xb0, 0x86, 0x09, 0xcd,
	0x5d, 0x32, 0x22, 0xcb, 0xab, 0x66, 0xdc, 0x29, 0x22, 0x29, 0xff, 0x10, 0xa3, 0x47, 0xc3, 0x21,
	0xa1, 0x54, 0xc0, 0x15, 0x3b, 0x5d, 0x1a, 0x6f, 0x43, 0xeb, 0x11, 0x61, 0xb3, 0xf9, 0x7f, 0xaa,
	0xdb, 0x9f, 0x11, 0x5c, 0xe6, 0x7d, 0x65, 0x86, 0x16, 0x13, 0xf4, 0x7e, 0x69, 0x82, 0xde, 0x28,
	0xb5, 0xc5, 0x02, 0x3a, 0xe9, 0x8d, 0xe9, 0xf0, 0xd4, 0xef, 0xcd, 0xc6, 0x5e, 0xae, 0x29, 0xa2,
	0xc2, 0xf7, 0xc4, 0xa2, 0x2f, 0x10, 0xe3, 0xb3, 0xf9, 0x68, 0x28, 0xfe, 0x10, 0x1a, 0xe2, 0x19,
	0x9d, 0x7c, 0xc3, 0x5b, 0xcb, 0x85, 0x94, 0xa5, 0x0a, 0xee, 0xcc, 0xd2, 0xb8, 0x0f, 0xd7, 0x2c,
	0x97, 0x0d, 0x9f, 0xe7, 0xdf, 0x82, 0x5a, 0xe2, 0x4f, 0x7f, 0x57, 0xa4, 0xf9, 0x16, 0x28, 0x49,
	0x18, 0xb1, 0x57, 0xc9, 0x96, 0xe3, 0x38, 0xa8, 0xf1, 0xcd, 0x12, 0xe3, 0x0b, 0x47, 0xf5, 0x2d,
	0xe0, 0xb8, 0xcf, 0x16, 0xea, 0xd3, 0xc9, 0x1e, 0xa4, 0x54, 0xa4, 0xf4, 0xdb, 0x2c, 0xd7, 0x02,
	0x2a, 0x27, 0xb7, 0x80, 0x77, 0x01, 0xc7, 0x0c, 0x39, 0x53, 0xe5, 0xb7, 0xfe, 0xa8, 0x41, 0x83,
	0x83, 0xf6, 0x49, 0xf4, 0xc2, 0x1f, 0x12, 0xfc, 0x1e, 0xc8, 0xc9, 0xd7, 0x16, 0x7e, 0x23, 0x97,
	0x45, 0xf6, 0x05, 0xa6, 0x97, 0x67, 0x0c, 0xfe, 0x14, 0xd4, 0xd9, 0x4c, 0xc2, 0xeb, 0x0b, 0x46,
	0xa7, 0xbe, 0xe0, 0x80, 0xe2, 0xbb, 0x00, 0xd9, 0xc8, 0xc1, 0x5a, 0x0e, 0x56, 0x98, 0x44, 0xf3,
	0xf7, 0xde, 0x05, 0xc8, 0x7a, 0x5d, 0xc1, 0xb0, 0xd0, 0x02, 0xe7, 0x0d, 0x1f, 0x00, 0x64, 0x22,
	0x2a, 0x18, 0x16, 0x54, 0xa8, 0xbf, 0x39, 0xa7, 0xf6, 0x3d, 0xfe, 0x1f, 0x13, 0xde, 0x86, 0x95,
	0x3c, 0x21, 0xb0, 0x5e, 0x7c, 0xa8, 0xfc, 0xc3, 0xeb, 0x27, 0x52, 0x01, 0x3f, 0x81, 0xd5, 0x22,
	0xc1, 0xf1, 0x95, 0xd3, 0xb4, 0xa5, 0x9f, 0x76, 0x4a, 0x31, 0x85, 0x8d, 0x53, 0x58, 0x8a, 0xef,
	0xe4, 0x8c, 0x4f, 0x97, 0x82, 0x7e, 0x66, 0x28, 0xc5, 0x0f, 0xa1, 0x55, 0x62, 0x30, 0xbe, 0x3a,
	0x57, 0xbb, 0x33, 0x3c, 0xc5, 0x63, 0x68, 0x95, 0xf8, 0x5a, 0xf0, 0x33, 0xcf, 0xe5, 0x45, 0x65,
	0x79, 0x56, 0x17, 0xeb, 0xf7, 0xff, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x5f, 0xfd, 0xba, 0xba, 0x39,
	0x0f, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// PostServiceClient is the client API for PostService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PostServiceClient interface {
	GetPost(ctx context.Context, in *GetPostReq, opts ...grpc.CallOption) (*Post, error)
	ListPosts(ctx context.Context, in *ListPostsReq, opts ...grpc.CallOption) (*ListPostsRes, error)
	CreatePost(ctx context.Context, in *CreatePostReq, opts ...grpc.CallOption) (*Post, error)
	UpdatePost(ctx context.Context, in *UpdatePostReq, opts ...grpc.CallOption) (*Post, error)
	DeletePost(ctx context.Context, in *DeletePostReq, opts ...grpc.CallOption) (*empty.Empty, error)
	GetApplyPost(ctx context.Context, in *GetApplyPostReq, opts ...grpc.CallOption) (*ApplyPost, error)
	ListApplyPosts(ctx context.Context, in *ListApplyPostsReq, opts ...grpc.CallOption) (*ListApplyPostsRes, error)
	BatchGetApplyPostsByPostIDs(ctx context.Context, in *BatchGetApplyPostsByPostIDsReq, opts ...grpc.CallOption) (*BatchGetApplyPostsByPostIDsRes, error)
	CreateApplyPost(ctx context.Context, in *CreateApplyPostReq, opts ...grpc.CallOption) (*ApplyPost, error)
	DeleteApplyPost(ctx context.Context, in *DeleteApplyPostReq, opts ...grpc.CallOption) (*empty.Empty, error)
}

type postServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPostServiceClient(cc grpc.ClientConnInterface) PostServiceClient {
	return &postServiceClient{cc}
}

func (c *postServiceClient) GetPost(ctx context.Context, in *GetPostReq, opts ...grpc.CallOption) (*Post, error) {
	out := new(Post)
	err := c.cc.Invoke(ctx, "/post_grpc.PostService/GetPost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) ListPosts(ctx context.Context, in *ListPostsReq, opts ...grpc.CallOption) (*ListPostsRes, error) {
	out := new(ListPostsRes)
	err := c.cc.Invoke(ctx, "/post_grpc.PostService/ListPosts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) CreatePost(ctx context.Context, in *CreatePostReq, opts ...grpc.CallOption) (*Post, error) {
	out := new(Post)
	err := c.cc.Invoke(ctx, "/post_grpc.PostService/CreatePost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) UpdatePost(ctx context.Context, in *UpdatePostReq, opts ...grpc.CallOption) (*Post, error) {
	out := new(Post)
	err := c.cc.Invoke(ctx, "/post_grpc.PostService/UpdatePost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) DeletePost(ctx context.Context, in *DeletePostReq, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/post_grpc.PostService/DeletePost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) GetApplyPost(ctx context.Context, in *GetApplyPostReq, opts ...grpc.CallOption) (*ApplyPost, error) {
	out := new(ApplyPost)
	err := c.cc.Invoke(ctx, "/post_grpc.PostService/GetApplyPost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) ListApplyPosts(ctx context.Context, in *ListApplyPostsReq, opts ...grpc.CallOption) (*ListApplyPostsRes, error) {
	out := new(ListApplyPostsRes)
	err := c.cc.Invoke(ctx, "/post_grpc.PostService/ListApplyPosts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) BatchGetApplyPostsByPostIDs(ctx context.Context, in *BatchGetApplyPostsByPostIDsReq, opts ...grpc.CallOption) (*BatchGetApplyPostsByPostIDsRes, error) {
	out := new(BatchGetApplyPostsByPostIDsRes)
	err := c.cc.Invoke(ctx, "/post_grpc.PostService/BatchGetApplyPostsByPostIDs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) CreateApplyPost(ctx context.Context, in *CreateApplyPostReq, opts ...grpc.CallOption) (*ApplyPost, error) {
	out := new(ApplyPost)
	err := c.cc.Invoke(ctx, "/post_grpc.PostService/CreateApplyPost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postServiceClient) DeleteApplyPost(ctx context.Context, in *DeleteApplyPostReq, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/post_grpc.PostService/DeleteApplyPost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PostServiceServer is the server API for PostService service.
type PostServiceServer interface {
	GetPost(context.Context, *GetPostReq) (*Post, error)
	ListPosts(context.Context, *ListPostsReq) (*ListPostsRes, error)
	CreatePost(context.Context, *CreatePostReq) (*Post, error)
	UpdatePost(context.Context, *UpdatePostReq) (*Post, error)
	DeletePost(context.Context, *DeletePostReq) (*empty.Empty, error)
	GetApplyPost(context.Context, *GetApplyPostReq) (*ApplyPost, error)
	ListApplyPosts(context.Context, *ListApplyPostsReq) (*ListApplyPostsRes, error)
	BatchGetApplyPostsByPostIDs(context.Context, *BatchGetApplyPostsByPostIDsReq) (*BatchGetApplyPostsByPostIDsRes, error)
	CreateApplyPost(context.Context, *CreateApplyPostReq) (*ApplyPost, error)
	DeleteApplyPost(context.Context, *DeleteApplyPostReq) (*empty.Empty, error)
}

// UnimplementedPostServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPostServiceServer struct {
}

func (*UnimplementedPostServiceServer) GetPost(ctx context.Context, req *GetPostReq) (*Post, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPost not implemented")
}
func (*UnimplementedPostServiceServer) ListPosts(ctx context.Context, req *ListPostsReq) (*ListPostsRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPosts not implemented")
}
func (*UnimplementedPostServiceServer) CreatePost(ctx context.Context, req *CreatePostReq) (*Post, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePost not implemented")
}
func (*UnimplementedPostServiceServer) UpdatePost(ctx context.Context, req *UpdatePostReq) (*Post, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePost not implemented")
}
func (*UnimplementedPostServiceServer) DeletePost(ctx context.Context, req *DeletePostReq) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePost not implemented")
}
func (*UnimplementedPostServiceServer) GetApplyPost(ctx context.Context, req *GetApplyPostReq) (*ApplyPost, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetApplyPost not implemented")
}
func (*UnimplementedPostServiceServer) ListApplyPosts(ctx context.Context, req *ListApplyPostsReq) (*ListApplyPostsRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListApplyPosts not implemented")
}
func (*UnimplementedPostServiceServer) BatchGetApplyPostsByPostIDs(ctx context.Context, req *BatchGetApplyPostsByPostIDsReq) (*BatchGetApplyPostsByPostIDsRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchGetApplyPostsByPostIDs not implemented")
}
func (*UnimplementedPostServiceServer) CreateApplyPost(ctx context.Context, req *CreateApplyPostReq) (*ApplyPost, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateApplyPost not implemented")
}
func (*UnimplementedPostServiceServer) DeleteApplyPost(ctx context.Context, req *DeleteApplyPostReq) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteApplyPost not implemented")
}

func RegisterPostServiceServer(s *grpc.Server, srv PostServiceServer) {
	s.RegisterService(&_PostService_serviceDesc, srv)
}

func _PostService_GetPost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPostReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).GetPost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/post_grpc.PostService/GetPost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).GetPost(ctx, req.(*GetPostReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostService_ListPosts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPostsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).ListPosts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/post_grpc.PostService/ListPosts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).ListPosts(ctx, req.(*ListPostsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostService_CreatePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePostReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).CreatePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/post_grpc.PostService/CreatePost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).CreatePost(ctx, req.(*CreatePostReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostService_UpdatePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePostReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).UpdatePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/post_grpc.PostService/UpdatePost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).UpdatePost(ctx, req.(*UpdatePostReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostService_DeletePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePostReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).DeletePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/post_grpc.PostService/DeletePost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).DeletePost(ctx, req.(*DeletePostReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostService_GetApplyPost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetApplyPostReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).GetApplyPost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/post_grpc.PostService/GetApplyPost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).GetApplyPost(ctx, req.(*GetApplyPostReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostService_ListApplyPosts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListApplyPostsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).ListApplyPosts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/post_grpc.PostService/ListApplyPosts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).ListApplyPosts(ctx, req.(*ListApplyPostsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostService_BatchGetApplyPostsByPostIDs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchGetApplyPostsByPostIDsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).BatchGetApplyPostsByPostIDs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/post_grpc.PostService/BatchGetApplyPostsByPostIDs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).BatchGetApplyPostsByPostIDs(ctx, req.(*BatchGetApplyPostsByPostIDsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostService_CreateApplyPost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateApplyPostReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).CreateApplyPost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/post_grpc.PostService/CreateApplyPost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).CreateApplyPost(ctx, req.(*CreateApplyPostReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PostService_DeleteApplyPost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteApplyPostReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).DeleteApplyPost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/post_grpc.PostService/DeleteApplyPost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).DeleteApplyPost(ctx, req.(*DeleteApplyPostReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _PostService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "post_grpc.PostService",
	HandlerType: (*PostServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPost",
			Handler:    _PostService_GetPost_Handler,
		},
		{
			MethodName: "ListPosts",
			Handler:    _PostService_ListPosts_Handler,
		},
		{
			MethodName: "CreatePost",
			Handler:    _PostService_CreatePost_Handler,
		},
		{
			MethodName: "UpdatePost",
			Handler:    _PostService_UpdatePost_Handler,
		},
		{
			MethodName: "DeletePost",
			Handler:    _PostService_DeletePost_Handler,
		},
		{
			MethodName: "GetApplyPost",
			Handler:    _PostService_GetApplyPost_Handler,
		},
		{
			MethodName: "ListApplyPosts",
			Handler:    _PostService_ListApplyPosts_Handler,
		},
		{
			MethodName: "BatchGetApplyPostsByPostIDs",
			Handler:    _PostService_BatchGetApplyPostsByPostIDs_Handler,
		},
		{
			MethodName: "CreateApplyPost",
			Handler:    _PostService_CreateApplyPost_Handler,
		},
		{
			MethodName: "DeleteApplyPost",
			Handler:    _PostService_DeleteApplyPost_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "post.proto",
}
