// Code generated by protoc-gen-go. DO NOT EDIT.
// source: src/controllers/profile_grpc/profile.proto

package profile_grpc

import (
	context "context"
	fmt "fmt"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Profile struct {
	Id                   int64                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string               `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	UserId               int64                `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Profile) Reset()         { *m = Profile{} }
func (m *Profile) String() string { return proto.CompactTextString(m) }
func (*Profile) ProtoMessage()    {}
func (*Profile) Descriptor() ([]byte, []int) {
	return fileDescriptor_37f0dbc3a895b8d9, []int{0}
}

func (m *Profile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Profile.Unmarshal(m, b)
}
func (m *Profile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Profile.Marshal(b, m, deterministic)
}
func (m *Profile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Profile.Merge(m, src)
}
func (m *Profile) XXX_Size() int {
	return xxx_messageInfo_Profile.Size(m)
}
func (m *Profile) XXX_DiscardUnknown() {
	xxx_messageInfo_Profile.DiscardUnknown(m)
}

var xxx_messageInfo_Profile proto.InternalMessageInfo

func (m *Profile) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Profile) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Profile) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *Profile) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Profile) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

type CreateReq struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	UserId               int64    `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateReq) Reset()         { *m = CreateReq{} }
func (m *CreateReq) String() string { return proto.CompactTextString(m) }
func (*CreateReq) ProtoMessage()    {}
func (*CreateReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_37f0dbc3a895b8d9, []int{1}
}

func (m *CreateReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateReq.Unmarshal(m, b)
}
func (m *CreateReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateReq.Marshal(b, m, deterministic)
}
func (m *CreateReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateReq.Merge(m, src)
}
func (m *CreateReq) XXX_Size() int {
	return xxx_messageInfo_CreateReq.Size(m)
}
func (m *CreateReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateReq proto.InternalMessageInfo

func (m *CreateReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type UpdateReq struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	UserId               int64    `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateReq) Reset()         { *m = UpdateReq{} }
func (m *UpdateReq) String() string { return proto.CompactTextString(m) }
func (*UpdateReq) ProtoMessage()    {}
func (*UpdateReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_37f0dbc3a895b8d9, []int{2}
}

func (m *UpdateReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateReq.Unmarshal(m, b)
}
func (m *UpdateReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateReq.Marshal(b, m, deterministic)
}
func (m *UpdateReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateReq.Merge(m, src)
}
func (m *UpdateReq) XXX_Size() int {
	return xxx_messageInfo_UpdateReq.Size(m)
}
func (m *UpdateReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateReq proto.InternalMessageInfo

func (m *UpdateReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type ID struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ID) Reset()         { *m = ID{} }
func (m *ID) String() string { return proto.CompactTextString(m) }
func (*ID) ProtoMessage()    {}
func (*ID) Descriptor() ([]byte, []int) {
	return fileDescriptor_37f0dbc3a895b8d9, []int{3}
}

func (m *ID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ID.Unmarshal(m, b)
}
func (m *ID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ID.Marshal(b, m, deterministic)
}
func (m *ID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ID.Merge(m, src)
}
func (m *ID) XXX_Size() int {
	return xxx_messageInfo_ID.Size(m)
}
func (m *ID) XXX_DiscardUnknown() {
	xxx_messageInfo_ID.DiscardUnknown(m)
}

var xxx_messageInfo_ID proto.InternalMessageInfo

func (m *ID) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func init() {
	proto.RegisterType((*Profile)(nil), "profile_grpc.Profile")
	proto.RegisterType((*CreateReq)(nil), "profile_grpc.CreateReq")
	proto.RegisterType((*UpdateReq)(nil), "profile_grpc.UpdateReq")
	proto.RegisterType((*ID)(nil), "profile_grpc.ID")
}

func init() {
	proto.RegisterFile("src/controllers/profile_grpc/profile.proto", fileDescriptor_37f0dbc3a895b8d9)
}

var fileDescriptor_37f0dbc3a895b8d9 = []byte{
	// 376 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x92, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0xd9, 0x34, 0xa6, 0x64, 0x2b, 0xa5, 0x2c, 0x48, 0x43, 0x40, 0x0d, 0x3d, 0x48, 0xf0,
	0x90, 0x40, 0x05, 0xa9, 0xc7, 0xc6, 0x80, 0x14, 0x3c, 0x48, 0xb4, 0x5e, 0xcb, 0x36, 0x99, 0x96,
	0xc0, 0xb6, 0x1b, 0x37, 0x9b, 0x8a, 0xdf, 0xcd, 0x8f, 0xe5, 0xa9, 0x27, 0xc9, 0xbf, 0xda, 0xd6,
	0x16, 0x2f, 0xde, 0x76, 0x3a, 0xbf, 0x79, 0x6f, 0x5e, 0x27, 0xf8, 0x3a, 0x15, 0xa1, 0x1b, 0xf2,
	0xa5, 0x14, 0x9c, 0x31, 0x10, 0xa9, 0x9b, 0x08, 0x3e, 0x8b, 0x19, 0x4c, 0xe6, 0x22, 0x09, 0xeb,
	0xc2, 0x49, 0x04, 0x97, 0x9c, 0x9c, 0x6e, 0xf7, 0xcc, 0xee, 0x8a, 0xb2, 0x38, 0xa2, 0x12, 0xdc,
	0xfa, 0x51, 0x62, 0xe6, 0xe5, 0x9c, 0xf3, 0x39, 0x03, 0xb7, 0xa8, 0xa6, 0xd9, 0xcc, 0x95, 0xf1,
	0x02, 0x52, 0x49, 0x17, 0x49, 0x05, 0x5c, 0xec, 0x03, 0xef, 0x82, 0x26, 0x09, 0x88, 0xb4, 0xec,
	0xf7, 0x3e, 0x11, 0x6e, 0x3e, 0x95, 0x56, 0xa4, 0x8d, 0x95, 0x38, 0x32, 0x90, 0x85, 0xec, 0x46,
	0xa0, 0xc4, 0x11, 0x21, 0x58, 0x5d, 0xd2, 0x05, 0x18, 0x8a, 0x85, 0x6c, 0x3d, 0x28, 0xde, 0xa4,
	0x8b, 0x9b, 0x59, 0x0a, 0x62, 0x12, 0x47, 0x46, 0xa3, 0x00, 0xb5, 0xbc, 0x1c, 0x45, 0xe4, 0x0e,
	0xe3, 0x50, 0x00, 0x95, 0x10, 0x4d, 0xa8, 0x34, 0x54, 0x0b, 0xd9, 0xad, 0xbe, 0xe9, 0x94, 0xee,
	0x4e, 0xed, 0xee, 0xbc, 0xd4, 0xeb, 0x05, 0x7a, 0x45, 0x0f, 0x65, 0x3e, 0x9a, 0x25, 0x51, 0x3d,
	0x7a, 0xf2, 0xf7, 0x68, 0x45, 0x0f, 0x65, 0xef, 0x11, 0xeb, 0xf7, 0x85, 0x4e, 0x00, 0x6f, 0xe4,
	0xbc, 0xda, 0x37, 0x4f, 0xa0, 0x7b, 0xfa, 0xda, 0xd3, 0x84, 0xda, 0x41, 0x06, 0xae, 0x56, 0xb7,
	0x7e, 0x56, 0xcf, 0x13, 0x35, 0xbc, 0xe6, 0xda, 0x53, 0x7b, 0x8a, 0x8d, 0xea, 0x0c, 0xb9, 0xda,
	0xb8, 0x90, 0xfe, 0x17, 0xb5, 0x2b, 0xac, 0x8c, 0xfc, 0x6d, 0x0e, 0x1d, 0xe4, 0xfa, 0x5f, 0x08,
	0xb7, 0xab, 0x13, 0x3c, 0x83, 0x58, 0xc5, 0x21, 0x90, 0x01, 0xd6, 0xca, 0x58, 0xa4, 0xeb, 0x6c,
	0x7f, 0x08, 0xce, 0x26, 0xac, 0x79, 0xb6, 0xdb, 0xa8, 0x6f, 0x78, 0x8b, 0x5b, 0x0f, 0x20, 0xbd,
	0x8f, 0x71, 0xae, 0xed, 0x93, 0xce, 0x2e, 0x35, 0xf2, 0x8f, 0xcd, 0x0d, 0xb0, 0x56, 0x46, 0xdf,
	0x77, 0xdc, 0xfc, 0x21, 0xc7, 0x1d, 0x35, 0x1f, 0x18, 0x48, 0x38, 0x60, 0xf6, 0xfb, 0x8a, 0x1e,
	0xe7, 0xec, 0x95, 0xb2, 0x0c, 0xa6, 0x5a, 0xf1, 0xdb, 0xcd, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x6e, 0x27, 0xd9, 0x02, 0x16, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ProfileServiceClient is the client API for ProfileService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProfileServiceClient interface {
	Create(ctx context.Context, in *CreateReq, opts ...grpc.CallOption) (*Profile, error)
	GetByUserID(ctx context.Context, in *ID, opts ...grpc.CallOption) (*Profile, error)
	Update(ctx context.Context, in *UpdateReq, opts ...grpc.CallOption) (*Profile, error)
	Delete(ctx context.Context, in *ID, opts ...grpc.CallOption) (*wrappers.BoolValue, error)
}

type profileServiceClient struct {
	cc *grpc.ClientConn
}

func NewProfileServiceClient(cc *grpc.ClientConn) ProfileServiceClient {
	return &profileServiceClient{cc}
}

func (c *profileServiceClient) Create(ctx context.Context, in *CreateReq, opts ...grpc.CallOption) (*Profile, error) {
	out := new(Profile)
	err := c.cc.Invoke(ctx, "/profile_grpc.ProfileService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) GetByUserID(ctx context.Context, in *ID, opts ...grpc.CallOption) (*Profile, error) {
	out := new(Profile)
	err := c.cc.Invoke(ctx, "/profile_grpc.ProfileService/GetByUserID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) Update(ctx context.Context, in *UpdateReq, opts ...grpc.CallOption) (*Profile, error) {
	out := new(Profile)
	err := c.cc.Invoke(ctx, "/profile_grpc.ProfileService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) Delete(ctx context.Context, in *ID, opts ...grpc.CallOption) (*wrappers.BoolValue, error) {
	out := new(wrappers.BoolValue)
	err := c.cc.Invoke(ctx, "/profile_grpc.ProfileService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProfileServiceServer is the server API for ProfileService service.
type ProfileServiceServer interface {
	Create(context.Context, *CreateReq) (*Profile, error)
	GetByUserID(context.Context, *ID) (*Profile, error)
	Update(context.Context, *UpdateReq) (*Profile, error)
	Delete(context.Context, *ID) (*wrappers.BoolValue, error)
}

// UnimplementedProfileServiceServer can be embedded to have forward compatible implementations.
type UnimplementedProfileServiceServer struct {
}

func (*UnimplementedProfileServiceServer) Create(ctx context.Context, req *CreateReq) (*Profile, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedProfileServiceServer) GetByUserID(ctx context.Context, req *ID) (*Profile, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetByUserID not implemented")
}
func (*UnimplementedProfileServiceServer) Update(ctx context.Context, req *UpdateReq) (*Profile, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (*UnimplementedProfileServiceServer) Delete(ctx context.Context, req *ID) (*wrappers.BoolValue, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}

func RegisterProfileServiceServer(s *grpc.Server, srv ProfileServiceServer) {
	s.RegisterService(&_ProfileService_serviceDesc, srv)
}

func _ProfileService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/profile_grpc.ProfileService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).Create(ctx, req.(*CreateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_GetByUserID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).GetByUserID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/profile_grpc.ProfileService/GetByUserID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).GetByUserID(ctx, req.(*ID))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/profile_grpc.ProfileService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).Update(ctx, req.(*UpdateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/profile_grpc.ProfileService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).Delete(ctx, req.(*ID))
	}
	return interceptor(ctx, in, info, handler)
}

var _ProfileService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "profile_grpc.ProfileService",
	HandlerType: (*ProfileServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _ProfileService_Create_Handler,
		},
		{
			MethodName: "GetByUserID",
			Handler:    _ProfileService_GetByUserID_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _ProfileService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _ProfileService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "src/controllers/profile_grpc/profile.proto",
}
