// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

import (
	"time"
)

type CreatePostInput struct {
	Title   string `json:"title"`
	Content string `json:"content"`
}

type GetPostListInput struct {
	Num      int       `json:"num"`
	Datetime time.Time `json:"datetime"`
}

type UpdatePostInput struct {
	ID      string `json:"id"`
	Title   string `json:"title"`
	Content string `json:"content"`
}
