// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

import (
	"time"

	graphql1 "github.com/ezio1119/fishapp-api-gateway/domain/graphql"
)

type CreatePostInput struct {
	Title   string `json:"title"`
	Content string `json:"content"`
}

type CreateUserInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type GetPostListInput struct {
	Num      int       `json:"num"`
	Datetime time.Time `json:"datetime"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type UpdatePostInput struct {
	ID      string `json:"id"`
	Title   string `json:"title"`
	Content string `json:"content"`
}

type UpdateUserInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type UserWithToken struct {
	User      *graphql1.User      `json:"user"`
	TokenPair *graphql1.TokenPair `json:"tokenPair"`
}
